environment:
  matrix:
    - nodejs_version: "10"

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - choco upgrade googlechrome
  - dir C:\avvm\node            # Print available versions of Node.js in AppVeyor
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm set progress=false
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build

# Don't actually build.
build: off
